### ISSUE TITLE
how can i use the damage method

### ISSUE THREAD

**Issue by twrtw** [Goodbird-git/CustomNPCPlus1.16.5#1]
public void damage(float damage, IEntity source) {
        if(source.getType() == 1)
            entity.hurt(new EntityDamageSource("player",source.getMCEntity()),damage);
        else
            entity.hurt(new EntityDamageSource(source.getTypeName(),source.getMCEntity()),damage);
    }

how can i use the method,i use it like that,but it doesn't work:
function interact(c){
var npc=c.npc
var player=c.player
npc.damage(5,player)
}

**Comment by Goodbird-git** [comment]
Since this function uses the damage source linked to the player, it checks if the player can damage the npc. So the npc should have aggresive faction so that player could hurt the npc. Only then it will work.
Hopefully this will fix this issue

**Comment by twrtw** [comment]
i use the file "CustomNPCs v1.16.5.jar" in lib，then i use the method,it report error and say:"damage(): expected 1 args; got 2 in <script> at line number 2"

**Comment by Goodbird-git** [comment]
The file "CustomNPCs v1.16.5.jar" in lib is the base CNPC-0728 mod, it does not contain the damage method with source

**Comment by Goodbird-git** [comment]
You should download the fixed and changed mod from the release section
