### ISSUE TITLE
Port for 43.3.5

### ISSUE THREAD

**Issue by 704Prod** [Goodbird-git/CustomNPCPlus1.16.5#2]
Not sure if this is the right place to ask,:

But would you able to port a version for 1.19.2, **Forge 43.3.5**?
I have a server in development for the modpack I'm making and I'm pretty much done adding mods, but the server development would benefit **greatly** from this mod. It's literally all I'm missing and I'd be eternally grateful for a mod version that works with my server.

**Comment by Goodbird-git** [comment]
Ported and sent in the discord private message
